ExporterWeb/Models/Industry.cs
using System.Collections.Generic;

namespace ExporterWeb.Models
{
    public class Industry
    {
        public Industry()
        {
            Translations = new List<IndustryTranslation>();
        }
        public int Id { get; set; }
        public int Order { get; set; }
        public ICollection<IndustryTranslation>? Translations { get; set; }
    }
}

ExporterWeb/Pages/Admin/AboutRegion/Create.cshtml.cs
using ExporterWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using System.Threading.Tasks;
using ExporterWeb.Helpers.Services;

namespace ExporterWeb.Pages.Admin.AboutRegion
{
    public class CreateModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageResizeService _imageResizer;

        public CreateModel(ApplicationDbContext context, ImageResizeService imageResizer)
        {
            _context = context;
            _imageResizer = imageResizer;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (_context.AboutRegionContents!.Any(x => x.Lang == AboutRegionModel.Lang))
                return BadRequest();

            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.AboutRegionContents!.Add(AboutRegionModel);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }

#nullable disable
        [BindProperty]
        public AboutRegionModel AboutRegionModel { get; set; }
    }
}

ExporterWeb/Pages/Admin/AboutRegion/Edit.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ExporterWeb.Models;

namespace ExporterWeb.Pages.Admin.AboutRegion
{
    public class EditModel : PageModel
    {
        private readonly ApplicationDbContext _context;

        public EditModel(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            AboutRegionModel = await _context.AboutRegionContents!.FirstOrDefaultAsync(m => m.Lang == id);

            if (AboutRegionModel == null)
            {
                return NotFound();
            }
            return Page();
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(AboutRegionModel).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!AboutRegionModelExists(AboutRegionModel.Lang))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool AboutRegionModelExists(string id)
        {
            return _context.AboutRegionContents!.Any(e => e.Lang == id);
        }
        
        #nullable disable
        [BindProperty]
        public AboutRegionModel AboutRegionModel { get; set; }
    }
}

ExporterWeb/Pages/Admin/Industries/Create.cshtml.cs
using System.Threading.Tasks;
using ExporterWeb.Helpers;
using ExporterWeb.Helpers.Services;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ExporterWeb.Pages.Admin.Industries
{
    public class Create : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageService _imageService;

        public Create(ApplicationDbContext context, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        public void OnGet()
        {
            
        }
        
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            Industry industry = new Industry();
            var maxOrder = (await _context.Industries!.MaxAsync(x => (int?)x.Order)) ?? 0;
            industry.Order = maxOrder + 1;
            
            if (Image is { })
            {
                IndustryTranslation.Image = _imageService.Save(ImageTypes.IndustryImage, Image);
            }

            IndustryTranslation.Language = Languages.DefaultLanguage;
            industry.Translations!.Add(IndustryTranslation);
            await _context.Industries!.AddAsync(industry);
            try
            {
                await _context.SaveChangesAsync();
            }
            catch
            {
                if (Image is { })
                    _imageService.Delete(ImageTypes.NewsLogo, IndustryTranslation.Image!);
                throw;
            }
            return RedirectToPage("./Index");
        }

#nullable disable
        [BindProperty]
        public IndustryTranslation IndustryTranslation { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }
    }
}

ExporterWeb/Pages/Admin/Industries/CreateTranslation.cshtml.cs
using System.Threading.Tasks;
using ExporterWeb.Helpers;
using ExporterWeb.Helpers.Services;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ExporterWeb.Pages.Admin.Industries
{
    public class CreateTranslation : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageService _imageService;

        public CreateTranslation(ApplicationDbContext context, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        public IActionResult OnGet(int? industryId, string? lang)
        {
            if (industryId is null || lang is null)
            {
                return NotFound();
            }
            
            IndustryId = industryId.Value;
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            
            Translation.IndustryId = IndustryId;

            if (Image is { })
            {
                Translation.Image = _imageService.Save(ImageTypes.IndustryImage, Image);
            }

            await _context.IndustryTranslations!.AddAsync(Translation);

            try
            {
                await _context.SaveChangesAsync();
            }
            catch
            {
                if (Image is { })
                {
                    _imageService.Delete(ImageTypes.IndustryImage, Translation.Image!);
                }
                throw;
            }
            return RedirectToPage("./Index");
        }
        
        #nullable disable
        [BindProperty]
        public IndustryTranslation Translation { get; set; }

        [BindProperty]
        public int IndustryId { get; set; }

        [BindProperty(Name = "lang", SupportsGet = true)]
        public string Language { get; set; }
        
        [BindProperty]
        public IFormFile Image { get; set; }
    }
}

ExporterWeb/Pages/Admin/Industries/Edit.cshtml.cs
using System.Threading.Tasks;
using ExporterWeb.Helpers;
using ExporterWeb.Helpers.Services;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ExporterWeb.Pages.Admin.Industries
{
    public class Edit : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageService _imageService;

        public Edit(ApplicationDbContext context, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        public async Task<IActionResult> OnGet(int? id)
        {
            if (id is null)
            {
                return NotFound();
            }

            Industry = await _context.IndustryTranslations!.FirstOrDefaultAsync(i => i.Id == id);

            if (Industry is null)
            {
                return NotFound();
            }

            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int id)
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var industryToUpdate = await _context.IndustryTranslations!.FirstOrDefaultAsync(i => i.Id == id);

            if (industryToUpdate is null)
            {
                return NotFound();
            }

            var oldImage = industryToUpdate.Image;
            if (Image is { })
            {
                industryToUpdate.Image = _imageService.Save(ImageTypes.IndustryImage, Image);
            }

            if (!await TryUpdateModelAsync(
                industryToUpdate,
                "Industry",
                i => i.Name, i => i.Description))
            {
                return RedirectToPage("./Index");
            }
            
            try
            {
                await _context.SaveChangesAsync();
                if (oldImage is { } && Image is { })
                {
                    _imageService.Delete(ImageTypes.IndustryImage, oldImage);
                }
            }
            catch
            {
                if (Image is { })
                {
                    _imageService.Delete(ImageTypes.IndustryImage, Industry.Image!);
                }
                throw;
            }
            return RedirectToPage("./Index");
        }

        public async Task<IActionResult> OnPostDeleteImage(int id)
        {
            Industry = await _context.IndustryTranslations!.FindAsync(id);
            _imageService.Delete(ImageTypes.IndustryImage, Industry.Image!);
            Industry.Image = null;
            await _context.SaveChangesAsync();
            return StatusCode(StatusCodes.Status204NoContent);
        }

#nullable disable
        [BindProperty]
        public IndustryTranslation Industry { get; set; }
        [BindProperty]
        public IFormFile Image { get; set; }
    }
}

ExporterWeb/Pages/Admin/Industries/Index.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ExporterWeb.Areas.Identity.Authorization;
using ExporterWeb.Helpers;
using ExporterWeb.Helpers.Services;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace ExporterWeb.Pages.Admin.Industries
{
    [Authorize(Roles = Constants.AdministratorsRole)]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageService _imageService;

        public IndexModel(ApplicationDbContext context, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        public async Task<IActionResult> OnGetAsync()
        {
            SecondaryLanguages = Languages.WhiteList;
            SecondaryLanguages.Remove(Languages.DefaultLanguage);

            IndustryTranslations =  await _context.IndustryTranslations!
                .Include(i => i.Industry)
                .ThenInclude(i => i!.Translations)
                .Where(i => i.Language == Languages.DefaultLanguage)
                .OrderBy(x => x.Industry!.Order)
                .ToListAsync();

            return Page();
        }
        
        public async Task<IActionResult> OnPostDeleteIndustryAsync(int id)
        {
            var industry = await _context.Industries!
                .Include(i => i.Translations)
                .FirstOrDefaultAsync(i => i.Id == id);
            
            if (industry is null)
            {
                return NotFound();
            }
            
            _context.Remove(industry);
            await _context.SaveChangesAsync();
            
            industry.Translations!
                .Where(t => t.Image is { })
                .ToList()
                .ForEach(t => _imageService.Delete(ImageTypes.IndustryImage, t.Image!));

            return RedirectToPage("./Index");
        }
        
        public async Task<IActionResult> OnPostDeleteTranslationAsync(int id)
        {
            var industryTranslation = await _context.IndustryTranslations!
                .Include(i => i.Industry)
                .ThenInclude(i => i!.Translations)
                .FirstOrDefaultAsync(i => i.Id == id);
            
            if (industryTranslation is null)
            {
                return NotFound();
            }

            if (industryTranslation.Language == Languages.DefaultLanguage)
            {
                return BadRequest();
            }
        
            if (industryTranslation.Industry!.Translations!.Count == 1)
            {
                _context.Industries!.Remove(industryTranslation.Industry);
            }
            else
            {
                _context.IndustryTranslations!.Remove(industryTranslation);
            }
            
            await _context.SaveChangesAsync();

            if (industryTranslation.Image is { })
            {
                _imageService.Delete(ImageTypes.IndustryImage, industryTranslation.Image);
            }
            
            return RedirectToPage("./Index");
        }
        
        #nullable disable
        public IList<IndustryTranslation> IndustryTranslations { get; set; }

        public HashSet<string> SecondaryLanguages { get; private set; }
    }
}

ExporterWeb/Pages/Admin/News/Create.cshtml.cs
using ExporterWeb.Areas.Identity.Authorization;
using ExporterWeb.Helpers;
using ExporterWeb.Helpers.Services;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Threading.Tasks;

namespace ExporterWeb.Pages.Admin.News
{
    [Authorize(Roles = Constants.AdministratorsRole + ", " + Constants.ManagersRole)]
    public class CreateModel : BasePageModel
    {
        private readonly ApplicationDbContext _context;
        private readonly ImageService _imageService;

        public CreateModel(ApplicationDbContext context, IWebHostEnvironment appEnvironment, ImageService imageService)
        {
            _context = context;
            _imageService = imageService;
        }

        public IActionResult OnGet()
        {
            ViewData["WhiteListLanguages"] = new SelectList(Languages.WhiteList);
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(IFormFile? logo)
        {
            if (!ModelState.IsValid)
                return Page();

            var newsItem = new NewsModel { UserNameOwner = User.Identity.Name! };

            if (logo is { })
                newsItem.Logo = _imageService.Save(ImageType.NewsLogo, logo);

            if (await TryUpdateModelAsync(
                    newsItem,
                    nameof(NewsItem),
                    n => n.Name, n => n.Description, n => n.Language))
            {
                await _context.News!.AddAsync(newsItem);
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch
                {
                    if (logo is { })
                        _imageService.Delete(ImageType.NewsLogo, newsItem.Logo!);
                    throw;
                }
                return RedirectToPage("./Index");
            }
            return Page();
        }

#nullable disable
        [BindProperty]
        public NewsModel NewsItem { get; set; }
    }
}

ExporterWeb/Pages/Admin/Users/Create.cshtml.cs
using ExporterWeb.Areas.Identity.Authorization;
using ExporterWeb.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Threading.Tasks;

namespace ExporterWeb.Pages.Admin.Users
{
    [BindProperties]
    public class CreateModel : PageModel
    {
        private readonly UserManager<User> _userManager;

        public CreateModel(UserManager<User> userManager)
        {
            _userManager = userManager;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
                return Page();
            
            var user = new User(UserName);
            var result = await _userManager.CreateAsync(user, Password);

            if (result.Succeeded)
            {
                if (IsManager)
                    await _userManager.AddToRoleAsync(user, Constants.ManagersRole);
                if (IsAnalyst)
                    await _userManager.AddToRoleAsync(user, Constants.AnalystsRole);
                return RedirectToPage("./Index");
            }

            foreach (var error in result.Errors)
                ModelState.AddModelError(string.Empty, error.Description);

            return Page();
        }

#nullable disable
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool IsManager { get; set; }
        public bool IsAnalyst { get; set; }
    }
}

ExporterWeb/Pages/Admin/Industries/Create.cshtml
@page
@using ExporterWeb.Helpers
@model ExporterWeb.Pages.Admin.Industries.Create

@{
    Layout = "_AdminLayout";
}

<div class="container-fluid page__container">

    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a asp-page="/Admin/Index">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Отрасли</li>
                </ol>
            </nav>
            <h1 class="m-0">Добавление отрасли
                <img data-toggle="tooltip" data-placement="top" title="@Languages.ToRussian(Languages.DefaultLanguage)" class="language-switcher__flag" src="/img/flags/@(Languages.DefaultLanguage).svg" alt="Флаг">
            </h1>
        </div>
    </div>

    <div class="card card-form">
        <div class="row no-gutters">
            <div class="col-lg-12 card-form__body card-body">
                
                <form method="post" onsubmit="return Validate(this);" enctype="multipart/form-data">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="IndustryTranslation.Language" value="@Languages.DefaultLanguage">

                    <div class="form-group mb-4">
                        <label class="control-label">Загрузите изображение</label>
                        <input asp-for="Image" class="form-control-file" id="file-input" type="file" accept=".jpg,.png,.jpeg" placeholder="Выбрать файл"/>
                        <small id="passwordHelpInline" class="text-muted">Допустимые форматы: jpg, jpeg, png</small>
                    </div>
                    
                    <div class="form-group mb-4">
                        <label asp-for="IndustryTranslation.Name" class="control-label">Название</label>
                        <input asp-for="IndustryTranslation.Name" class="form-control"/>
                        <span asp-validation-for="IndustryTranslation.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="IndustryTranslation.Description" class="control-label">Описание</label>
                        <textarea asp-for="IndustryTranslation.Description" id="industry-description"></textarea>
                        <span asp-validation-for="IndustryTranslation.Description" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-0">
                        <input for type="submit" value="Создать" class="btn btn-primary"/>
                    </div>
                </form>
                
            </div>
        </div>
    </div>

</div>


@section Scripts {
    <script src="~/js/custom.js"></script>
    <script src="//cdn.ckeditor.com/4.15.1/full/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'industry-description', {
            filebrowserUploadUrl: '/api/upload/upload-industry-image'
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExporterWeb/Pages/Admin/Industries/Edit.cshtml
@page
@using ExporterWeb.Helpers
@model ExporterWeb.Pages.Admin.Industries.Edit

@{
    Layout = "_AdminLayout";
}

<div class="container-fluid page__container">

    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a asp-page="/Admin/Index">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Отрасли</li>
                </ol>
            </nav>
            <h1 class="m-0">Редактирование отрасли
                <img data-toggle="tooltip" data-placement="top" title="@Languages.ToRussian(Model.Industry.Language)"
                     class="language-switcher__flag" src="/img/flags/@(Model.Industry.Language).svg" alt="Флаг"/>
            </h1>
        </div>
        <div class="d-flex">
            @if (Model.Industry.Language != Languages.DefaultLanguage)
            {
                <form method="post"
                      asp-page="Index"
                      asp-page-handler="DeleteTranslation"
                      onsubmit="return confirm('Вы уверены что хотите удалить перевод этой отрасли?')">
                    <input type="hidden" name="id" value="@Model.Industry.Id"/>
                    <button class="btn btn-danger mr-2" type="submit">Удалить перевод</button>
                </form>
            }
           
        </div>
    </div>

    <div class="card card-form">
        <div class="row no-gutters">
            <div class="col-lg-12 card-form__body card-body">

                @if (Model.Industry.Image is {})
                {
                    <div id="current-image-row" class="form-group mb-2">
                        <div class="control-label mb-2">Изображение отрасли</div>
                        <img src="@Model.Industry.LogoPath()">

                        <form class="mt-1" method="post" id="delete-image-form">
                            <div class="form-group mb-4">
                                <button id="del-image-button" class="btn btn-danger" type="submit" asp-page-handler="DeleteImage">Удалить текущее изображение</button>
                            </div>
                        </form>
                    </div>

                    <style>
                        .upload-img-block {
                            display: none;
                        }
                    </style>
                }

                <form method="post" enctype="multipart/form-data">
                    
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Industry.Id">
                    <input type="hidden" asp-for="Industry.IndustryId">
                    <input type="hidden" asp-for="Industry.Language">
                    <input type="hidden" asp-for="Industry.Image" value="@Model.Industry.Image"/>

                    <div class="form-group mb-4 upload-img-block">
                        <label class="control-label">Загрузите изображение</label>
                        <input class="form-control-file" id="file-input" type="file" name="Image" accept=".jpg,.png,.jpeg" placeholder="Выбрать файл" />
                        <small id="passwordHelpInline" class="text-muted">Допустимые форматы: jpg, jpeg, png</small>
                    </div>

                    <div class="form-group mb-4">
                        <label asp-for="Industry.Name" class="control-label">Название</label>
                        <input asp-for="Industry.Name" class="form-control"/>
                        <span asp-validation-for="Industry.Name" class="text-danger"></span>
                    </div>
                    <div class="form-group mb-4">
                        <label asp-for="Industry.Description" class="control-label">Описание</label>
                        <textarea asp-for="Industry.Description" id="industry-description"></textarea>
                        <span asp-validation-for="Industry.Description" class="text-danger"></span>
                    </div>
                    
                    <div class="form-group mb-0">
                        <input type="submit" value="Сохранить" class="btn btn-primary"/>
                    </div>
                </form>

            </div>

        </div>
    </div>

</div>


@section Scripts {
    <script src="~/js/custom.js"></script>
    <script src="//cdn.ckeditor.com/4.15.1/full/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'industry-description', {
            filebrowserUploadUrl: '/api/upload/upload-industry-image'
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ExporterWeb/Pages/Admin/Industries/Index.cshtml
@page
@using ExporterWeb.Helpers
@model ExporterWeb.Pages.Admin.Industries.IndexModel

@{
    Layout = "_AdminLayout";
}

@section Styles {
    <style>
        .table thead th {
            font-size: 15px !important;
        }
    </style>
}

<div class="container-fluid page__container">

    <div class="page__heading d-flex align-items-center">
        <div class="flex">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb mb-0">
                    <li class="breadcrumb-item"><a asp-page="/Admin/Index">Главная</a></li>
                    <li class="breadcrumb-item active" aria-current="page">Отрасли</li>
                </ol>
            </nav>
            <h1 class="m-0 mt-2">Отрасли</h1>
        </div>
        <div class="d-flex align-items-center">
            <a asp-page="./Create" class="btn btn-success mr-2">Добавить отрасль</a>
        </div>
    </div>

    <div class="card card-form">
        <div class="row no-gutters">
            <div class="col-lg-12 card-form__body card-body">
                
                <div class="table-responsive" data-toggle="lists" data-lists-values='["js-lists-values-employee-name"]'>

                    <table class="table table-striped table-hover">
                        <thead>
                        <tr>
                            <th scope="col" width="30">#</th>
                            <th scope="col">
                                Название
                            </th>
                            <th>
                                @foreach (var lang in Model.SecondaryLanguages)
                                {
                                    <span style="width:70px;" class="mx-1"><img title="@Languages.ToRussian(lang)" class="language-switcher__flag" src="/img/flags/@(lang).svg" alt="Флаг"/></span>
                                }
                            </th>
                            <th style="text-align: right">
                                Действия
                            </th>
                        </tr>
                        </thead>
                        <tbody class="list">
                        @for(var i = 0; i < Model.IndustryTranslations.Count; i++)
                        {
                            <tr>
                                <td>@(i + 1).</td>
                                <td>
                                    <a asp-page="./Edit" asp-route-id="@Model.IndustryTranslations[i].Id">@Model.IndustryTranslations[i].Name</a>
                                </td>
                                <td>
                                
                                    @foreach (var lang in Model.SecondaryLanguages)
                                    {
                                        if (Model.IndustryTranslations[i].Industry!.Translations!.Any(translation => translation.Language == lang))
                                        {
                                            var translationId = Model.IndustryTranslations[i].Industry.Translations.FirstOrDefault(t => t.Language == lang)!.Id;
                                            <span style="width:70px;"><a asp-page="./Edit" asp-route-id="@translationId"><i class="material-icons">create</i></a></span>
                                        }
                                        else
                                        {
                                            <span style="width:70px;"><a asp-page="./CreateTranslation" asp-route-lang="@lang" asp-route-industryId="@Model.IndustryTranslations[i].IndustryId"><i class="material-icons">add_box</i></a></span>
                                        }
                                    }
                                
                                </td>
                                <td style="text-align:right">
                                    <div class="d-flex align-content-center justify-content-end">
                                        <form id="delete-industry" method="post" asp-page-handler="DeleteIndustry" onsubmit="return confirm('Вы действительно хотите удалить @Model.IndustryTranslations[i].Name? При подтверждении удалится вся информация об этой отрасли на всех языках')">
                                            <input type="hidden" name="id" value="@Model.IndustryTranslations[i].IndustryId">
                                            <button type="submit" class="btn btn-rounded btn-danger btn-sm">Удалить</button>
                                        </form>
                                    </div>
                                </td>
                            </tr>
                        }
                        </tbody>
                    </table>
                </div>
                
            </div>
        </div>
    </div>
    
</div>